services:
  minecraft-server:
    image: itzg/minecraft-server:latest
    container_name: minecraft-server
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "YOUR RCON PASSWORD HERE" 
      VERSION: "LATEST"
      MAX_TICK_TIME: -1
    volumes:
      - ./data:/data
    networks:
      - minecraft_default
      - proxy
    restart: unless-stopped

  mcnator:
    build: .
    container_name: mcnator 
    environment:
      TOKEN: "YOUR DISCORD TOKEN HERE" 
      CHANNEL_ID: YOUR CHANEL ID HERE 
      RCON_PASSWORD: "YOUR RCON PASSWORD HERE" 
    volumes:
      - ./data/logs:/app/logs:ro
    networks:
      - minecraft_default
    restart: unless-stopped

networks:
  minecraft_default:
    driver: bridge
  proxy:
    external: true
